---
apiVersion: v1
kind: Pod
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  containers:
  - name: vault
    image: hashicorp/vault:latest
    ports:
    - containerPort: 8200
    securityContext:
      capabilities:
        add:
          - IPC_LOCK
    env:
    - name: VAULT_ADDR
      value: "http://127.0.0.1:8200"
    volumeMounts:
    - name: vault-config
      mountPath: /vault/config
    - name: vault-data
      mountPath: /opt/vault
    args:
    - "server"
    - "-config=/vault/config/vault.hcl"
  volumes:
  - name: vault-config
    configMap:
      name: vault-config
  - name: vault-data
    persistentVolumeClaim:
      claimName: vault-data-claim