---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-data-volume
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  storageClassName: vault-data-volume
  hostPath:
    path: /data/vault
