---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data-claim
  namespace: vault
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: vault-data-volume